// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search-bleak.proto

package go_micro_srv_tutu_search_bleak

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShieldDateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Match                string   `protobuf:"bytes,2,opt,name=Match,proto3" json:"Match,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=Operation,proto3" json:"Operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShieldDateRequest) Reset()         { *m = ShieldDateRequest{} }
func (m *ShieldDateRequest) String() string { return proto.CompactTextString(m) }
func (*ShieldDateRequest) ProtoMessage()    {}
func (*ShieldDateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac5470cb553d847, []int{0}
}

func (m *ShieldDateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShieldDateRequest.Unmarshal(m, b)
}
func (m *ShieldDateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShieldDateRequest.Marshal(b, m, deterministic)
}
func (m *ShieldDateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShieldDateRequest.Merge(m, src)
}
func (m *ShieldDateRequest) XXX_Size() int {
	return xxx_messageInfo_ShieldDateRequest.Size(m)
}
func (m *ShieldDateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShieldDateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShieldDateRequest proto.InternalMessageInfo

func (m *ShieldDateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShieldDateRequest) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *ShieldDateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

type CheckWord struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=Keyword,proto3" json:"Keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckWord) Reset()         { *m = CheckWord{} }
func (m *CheckWord) String() string { return proto.CompactTextString(m) }
func (*CheckWord) ProtoMessage()    {}
func (*CheckWord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac5470cb553d847, []int{1}
}

func (m *CheckWord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckWord.Unmarshal(m, b)
}
func (m *CheckWord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckWord.Marshal(b, m, deterministic)
}
func (m *CheckWord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckWord.Merge(m, src)
}
func (m *CheckWord) XXX_Size() int {
	return xxx_messageInfo_CheckWord.Size(m)
}
func (m *CheckWord) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckWord.DiscardUnknown(m)
}

var xxx_messageInfo_CheckWord proto.InternalMessageInfo

func (m *CheckWord) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type Response struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac5470cb553d847, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Status struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ac5470cb553d847, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*ShieldDateRequest)(nil), "go.micro.srv.search_shield.ShieldDateRequest")
	proto.RegisterType((*CheckWord)(nil), "go.micro.srv.search_shield.CheckWord")
	proto.RegisterType((*Response)(nil), "go.micro.srv.search_shield.Response")
	proto.RegisterType((*Status)(nil), "go.micro.srv.search_shield.Status")
}

func init() { proto.RegisterFile("search-bleak.proto", fileDescriptor_7ac5470cb553d847) }

var fileDescriptor_7ac5470cb553d847 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0xfd, 0x6d, 0xfb, 0xb3, 0xba, 0x53, 0x11, 0x1d, 0x3c, 0x2c, 0x22, 0x52, 0x16, 0x94, 0x7a,
	0x30, 0x60, 0xbd, 0x7b, 0xb0, 0xbd, 0x54, 0x29, 0x42, 0xaa, 0xf4, 0x66, 0x49, 0x37, 0x43, 0x77,
	0xe9, 0x9f, 0x6c, 0x93, 0xac, 0xe2, 0x27, 0xf6, 0x6b, 0x48, 0xb3, 0x69, 0x15, 0x0f, 0x2e, 0xde,
	0x66, 0x32, 0xef, 0xe5, 0xbd, 0x79, 0x09, 0xa0, 0x21, 0xa1, 0x93, 0xf4, 0x6a, 0x32, 0x27, 0x31,
	0x63, 0xb9, 0x56, 0x56, 0xe1, 0xd9, 0x54, 0xb1, 0x45, 0x96, 0x68, 0xc5, 0x8c, 0x7e, 0x65, 0xb6,
	0xb0, 0xc5, 0xb8, 0x44, 0x8d, 0x1d, 0x2a, 0x1e, 0xc1, 0xd1, 0x30, 0xcd, 0x68, 0x2e, 0x7b, 0xc2,
	0x12, 0xa7, 0x55, 0x41, 0xc6, 0xe2, 0x01, 0xd4, 0xfa, 0x32, 0x0a, 0x5a, 0x41, 0xbb, 0xce, 0x6b,
	0x7d, 0x89, 0xc7, 0xb0, 0x33, 0x10, 0x36, 0x49, 0xa3, 0x5a, 0x2b, 0x68, 0x87, 0xbc, 0x6c, 0xf0,
	0x14, 0xc2, 0xc7, 0x9c, 0xb4, 0xb0, 0x99, 0x5a, 0x46, 0x75, 0x37, 0xf9, 0x3a, 0x88, 0xcf, 0x21,
	0xec, 0xa6, 0x94, 0xcc, 0x46, 0x4a, 0x4b, 0x8c, 0x60, 0xf7, 0x81, 0xde, 0xdf, 0x94, 0x2e, 0x6f,
	0x0d, 0xf9, 0xa6, 0x8d, 0x5f, 0x60, 0x8f, 0x93, 0xc9, 0xd5, 0xd2, 0x10, 0xde, 0x42, 0x63, 0x68,
	0x85, 0x2d, 0x8c, 0x03, 0x35, 0x3b, 0x17, 0xec, 0x77, 0xf3, 0xac, 0x44, 0x73, 0xcf, 0x42, 0x84,
	0xff, 0x3d, 0x61, 0x85, 0x77, 0xe9, 0xea, 0xf8, 0x1e, 0xbe, 0x4d, 0xbb, 0x4a, 0x92, 0x5f, 0xcb,
	0xd5, 0x6b, 0x5f, 0x03, 0x32, 0x46, 0x4c, 0xc9, 0x93, 0x36, 0xed, 0x1a, 0xfd, 0x94, 0x2d, 0xc8,
	0xef, 0xe5, 0xea, 0xce, 0x47, 0x00, 0xcd, 0xa1, 0xd3, 0xbf, 0x5b, 0xcb, 0xe3, 0x0a, 0x0e, 0x9f,
	0x73, 0x29, 0x2c, 0x6d, 0x13, 0x14, 0x78, 0x5d, 0xe9, 0xf9, 0x67, 0xda, 0x27, 0xed, 0x2a, 0xca,
	0x26, 0xa0, 0xf8, 0x1f, 0x12, 0xec, 0xbb, 0x54, 0x7d, 0x7c, 0x78, 0x59, 0xc5, 0xdd, 0xbe, 0xc1,
	0x5f, 0x64, 0x26, 0x0d, 0xf7, 0x79, 0x6e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40, 0xaf, 0x97,
	0xc4, 0x52, 0x02, 0x00, 0x00,
}
